### ISSUE TITLE
Possible undefined behavior in normalize function

### ISSUE THREAD

**Issue by hkalodner** [chfast/intx#174]
XCode's analyzer (through clang) is reporting possible undefined behavior in the normalize function, reached through a call to `to_string`. The issue occurs at https://github.com/chfast/intx/blob/732522a5c10227782fc844c0411482b27a5e11ed/include/intx/intx.hpp#L712 where `v[i]` is left shifted by `na.shift` bits. When `na.shift == 64` this is undefined behavior. It looks like one possible solution to this would be to just set `v[i] = v[i - 1]` when `na.shift == 64`.

I've attached the execution trace that xcode produced, but the issue seems easy to produce `na.shift == 64` when `v[n - 1] == 0` due to the `clz` function.

> intx/int128.hpp:858:1: Entered call from 'operator<<'
> intx/int128.hpp:863:9: Assuming the condition is false
> intx/int128.hpp:867:12: Entering loop body
> intx/int128.hpp:870:26: Calling 'udivrem<256>'
> intx/intx.hpp:858:1: Entered call from 'to_string<256>'
> intx/intx.hpp:860:15: Calling 'normalize<intx::uint<256>>'
> intx/intx.hpp:687:24: Entered call from 'udivrem<256>'
> intx/intx.hpp:701:34: Assuming the condition is false
> intx/intx.hpp:701:25: Loop body executed 0 times
> intx/intx.hpp:705:25: Loop body executed 0 times
> intx/intx.hpp:708:16: Calling 'clz'
> intx/int128.hpp:476:1: Entered call from 'normalize<intx::uint<256>>'
> intx/int128.hpp:481:12: Assuming 'x' is equal to 0
> intx/int128.hpp:481:5: Returning the value 64, which participates in a condition later
> intx/int128.hpp:481:5: Returning the value 64
> intx/intx.hpp:708:16: Returning from 'clz'
> intx/intx.hpp:708:5: The value 64 is assigned to 'na.shift'
> intx/intx.hpp:711:37: Entering loop body
> intx/intx.hpp:711:9: Looping back to the head of the loop
> intx/intx.hpp:711:37: Entering loop body
> intx/intx.hpp:711:9: Looping back to the head of the loop
> intx/intx.hpp:711:37: Entering loop body
> intx/intx.hpp:712:27: The result of the left shift is undefined due to shifting by '64', which is greater or equal to the width of type 'unsigned long long'

**Comment by chfast** [comment]
Hi @hkalodner, thanks for the report.

This can happen if you divide by 0. I have not added explicit checks/conditions to handle division by 0 so you get undefined behavior as with primitive integer types in C++.

However, in https://github.com/chfast/intx/pull/168 I added some additional checks what may report error in Debug and UBSan builds. I will check if these handle the case you reported.

Do you know how exactly this clang analyzer is being called? I would be interested in incorporate that to CI.
