### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by greg7mdp** [chfast/intx#266]
Hi Pawel, instead of having `#if INTX_HAS_BUILTIN_INT128` in multiple APIs, why not just do:
```
#if INTX_HAS_BUILTIN_INT128
    using uint128 = builtin_uint128;
#else
    using uint128 = uint<128>;
#endif
```

**Comment by greg7mdp** [comment]
Never mind, I think I understand why it is more practical to do it your way.

**Comment by chfast** [comment]
We really want to use `umul` instruction which does 64x64 → 128 multiplication. The way to get it on GCC and Clang is to use `__int128` type. On MSVC there is the intrinsic.
