### ISSUE TITLE
Simplify literal API

### ISSUE THREAD

**Issue by axic** [chfast/intx#81]
Currently there is `from_string<>` and the literal operator, one supports hexadecimal, the other doesn't.

I think this should be made consistent.

Should also introduce `to_hex_string()` next to `to_string()`.

**Comment by chfast** [comment]
The `to_string()` maps the `std::to_string()`. There is not option for hex output in `std`.

How about we name it just `hex()` as in https://github.com/chfast/evmone/blob/master/test/utils/utils.hpp#L14?

**Comment by axic** [comment]
`hex()` is fine with me.

The bigger issue is with the *from* direction. The constructors are inconsistent and `from_string` also accept invalid input.

**Comment by chfast** [comment]
I will fixed that.

**Comment by chfast** [comment]
Literals and `from_string` fixed by https://github.com/chfast/intx/pull/88.
